name: mvcolight
channels:
  - defaults
dependencies:
  - pip=25.2
  - python=3.11.13
  - setuptools=78.1.1
  - sqlite=3.50.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - diff-gaussian-rasterization==0.0.0
      - easydict==1.13
      - einops==0.8.1
      - filelock==3.19.1
      - fonttools==4.59.2
      - fsspec==2025.9.0
      - fused-ssim==0.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - jaxtyping==0.3.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - lpips==0.1.4
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mmengine==0.10.7
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plyfile==1.1.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2025.9.1
      - requests==2.32.5
      - rich==14.1.0
      - safetensors==0.6.2
      - scipy==1.16.1
      - sentry-sdk==2.35.2
      - simple-knn==0.0.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - thop==0.1.1-2209072238
      - timm==1.0.19
      - tokenizers==0.22.0
      - torch==2.3.1+cu121
      - torchaudio==2.3.1+cu121
      - torchmetrics==1.8.2
      - torchvision==0.18.1+cu121
      - tqdm==4.67.1
      - transformers==4.56.0
      - triton==2.3.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - wadler-lindig==0.1.7
      - wandb==0.21.3
      - werkzeug==3.1.3
      - yapf==0.43.0
