experiment_name: dtc_multilight_l

log_dir: ./logs
evaluation: false

use_wandb: false
wandb_project: 2d_object_compositing

use_amp: true
amp_dtype: fp16 

# model Parameters
model:
  type: SwinT2D
  img_size: 256
  patch_size: 16
  embed_dim: 192
  depths: [6, 6, 6]
  num_heads: [6, 6, 6]
  window_size: 8

# loss Parameters
loss:
  type: Loss2D
  coef: 0.05

# data Parameters
dataset:
  train:
    type: DTCMultiLight2D
    stage: train
    data_json: configs/2d/data_json/dtc_multilight/train.json
    image_size: [256, 256]
    num_context_views: 1
    num_target_views: 1
    add_background: true
    add_depth: true
  test:
    type: DTCMultiLight2D
    stage: test
    data_json: configs/2d/data_json/dtc_multilight/test.json
    image_size: [256, 256]
    num_context_views: 16
    num_target_views: 16
    add_background: true
    add_depth: true
    
training:
  port: 35266
  # dataset Parameters
  batch_size: 8
  num_workers: 16
  persistent_workers: true
  
  # optim Parameters
  max_iterations: 1000000
  grad_accum_steps: 1
  weight_decay: 0.05
  lr: 2e-4
  warmup_steps: 10000
  scheduler_type: cosine
  beta1: 0.9
  beta2: 0.95
  ema_beta: 0.99
  resume_ckpt: null
  resume_optimizer: true

  # Checkpoint Parameters
  save_interval: 100000
  vis_every: 1000

  allowed_gradnorm_factor: 100.0
  grad_clip_norm: 1.0
